# Build the react app
yarn build

# Copy files to dist folder
cp build/index.html dist/assets/index.html
cp build/static/css/*.css dist/assets/
cp build/static/js/*.js dist/assets/

# Rename paths inside index.html to link to new css and js locations
sed -i -e 's/\/static\/css\///g' dist/assets/index.html
sed -i -e 's/\/static\/js\///g' dist/assets/index.html

# Remove -e file generated by sed
rm dist/assets/index.html-e

# Rename iframe url in zat manifest
sed -i -e 's/iframe/index/g' dist/manifest.json

# Remove -e file generated by sed... again
rm dist/manifest.json-e

# Package the app with zat
zat package --path dist

# Move the compiled app to the Desktop
mv dist/tmp/app*.zip ~/Desktop/Custom\ Resources\ Viewer.zip

# Revert the project back to a clean state
rm dist/.zat dist/assets/index.html dist/assets/main.*.js dist/assets/main.*.css
rm -rf dist/tmp
sed -i -e 's/index/iframe/g' dist/manifest.json
rm dist/manifest.json-e
rm -rf build

# Echo message to show compilation has completed.
echo "Custom Resources Viewer app has been compiled to ~/Desktop/Custom Resources Viewer.zip"